// This is an autogenerated file from Firebase Studio.
import { z } from 'zod';

export const medicationSchema = z.object({
  id: z.string().optional(), // keep id for consistency with type, but not strictly needed for validation if generated on add
  name: z.string().min(1, 'Medication name is required'),
  dosage: z.string().min(1, 'Dosage is required'),
  frequency: z.string().min(1, 'Frequency is required'),
});
export type MedicationFormData = z.infer<typeof medicationSchema>;


export const vitalSignsSchema = z.object({
  heartRate: z.string().optional().describe("Patient's heart rate in beats per minute (bpm)."),
  bloodPressureSystolic: z.string().optional().describe("Systolic blood pressure value in mmHg."),
  bloodPressureDiastolic: z.string().optional().describe("Diastolic blood pressure value in mmHg."),
  temperature: z.string().optional().describe("Body temperature, specify units (e.g., °C or °F)."),
  bloodSugar: z.string().optional().describe("Blood sugar level, specify units (e.g., mg/dL or mmol/L)."),
  oxygenSaturation: z.string().optional().describe("Blood oxygen saturation level as a percentage (SpO2)."),
});
export type VitalSignsFormData = z.infer<typeof vitalSignsSchema>;

export const habitsSchema = z.object({
  sleep: z.string().optional().describe("Description of sleep patterns or duration (e.g., '7 hours, restful')."),
  exercise: z.string().optional().describe("Description of physical activity (e.g., '30 min walk')."),
  diet: z.string().optional().describe("Notes about diet or meals (e.g., 'Balanced meals, avoided sugary drinks')."),
  mood: z.string().optional().describe("General mood or emotional state (e.g., 'Feeling calm')."),
});
export type HabitsFormData = z.infer<typeof habitsSchema>;
